const path = require('node:path');
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const url = value => value.split('/').map(encodeURIComponent).join('/');
function shell(title, content, prefix = './', active = 'batches') {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} · Glitch lab</title><link rel="stylesheet" href="${prefix}style.css"><script src="${prefix}gallery.js" defer></script></head><body><header><a class="brand" href="${prefix}index.html">GLITCH<span>LAB</span><small>LOCAL IMAGE STUDIO</small></a><nav aria-label="Main navigation"><a href="${prefix}index.html">Create</a><a ${active === 'batches' ? 'aria-current="page"' : ''} href="${prefix}batches.html">Batches</a><a ${active === 'favorites' ? 'aria-current="page"' : ''} href="${prefix}favorites/index.html">Favorites</a></nav></header><main>${content}</main><footer>JPEG experiments. Originals stay untouched.</footer></body></html>`;
}
function parameters(params) {
  return `<dl class="parameters">${Object.entries(params).map(([key, value]) => `<div><dt>${escape(key)}</dt><dd>${escape(value)}</dd></div>`).join('')}</dl>`;
}
function batch(batch) {
  const prefix = '../../../';
  const successful = batch.records.filter(r => !r.error);
  return shell(path.basename(batch.source), `<div class="eyebrow">BATCH / ${escape(batch.id.split('/').pop())}</div><div class="page-heading"><div><h1>${escape(path.basename(batch.source))}</h1><p>${successful.length} variations · ${batch.records.length - successful.length} failed · ${batch.maxWidth ? `${batch.maxWidth}px maximum width` : 'Original dimensions'}</p></div><a class="button secondary" href="${prefix}index.html">New experiment ↗</a></div><div class="batch-meta"><span>Random seed <code>${escape(batch.batchSeed)}</code></span><a href="manifest.json">Full batch settings ↗</a></div><p id="notice" role="status" aria-live="polite"></p><section class="gallery">${successful.map(record => {
    const file = record.favorite ? `${prefix}favorites/${url(record.favorite)}` : url(record.file);
    return `<article class="image-card"><a class="image-link" href="${file}"><img loading="lazy" src="${prefix}thumb/${record.favorite ? `favorites/${url(record.favorite)}` : `generatedimages/${url(batch.id)}/${url(record.file)}`}" data-original="${file}" alt="Glitch variation ${record.index}"></a><div class="card-body"><div class="card-heading"><h2>Variation ${String(record.index).padStart(3, '0')}</h2><span class="tag">${record.favorite ? 'FAVORITE' : escape(batch.format?.toUpperCase() || 'PNG')}</span></div>${parameters(record.params)}<div class="actions"><button data-batch="${escape(batch.id)}" data-index="${record.index}">${record.favorite ? 'Saved · stage again' : 'Save favorite'}</button><a download href="${file}">Download ↗</a></div></div></article>`;
  }).join('')}</section>${batch.records.some(r => r.error) ? `<details><summary>Failed variations</summary>${batch.records.filter(r => r.error).map(r => `<p>#${r.index}: ${escape(r.error)}</p>`).join('')}</details>` : ''}`, prefix);
}
function favorites(records) {
  return shell('Favorites', `<div class="eyebrow">THE KEEPERS</div><div class="page-heading"><div><h1>Favorites<span class="count">${records.length}</span></h1><p>Saved images and their recipes, ready for Git.</p></div><a class="button secondary" href="../index.html">New experiment ↗</a></div>${records.length ? `<section class="gallery">${records.map(record => `<article class="image-card"><a class="image-link" href="${url(record.id)}/${url(record.file)}"><img loading="lazy" src="../thumb/favorites/${url(record.id)}/${url(record.file)}" data-original="${url(record.id)}/${url(record.file)}" alt="Favorite glitch of ${escape(record.source)}"></a><div class="card-body"><div class="card-heading"><h2>${escape(record.source)}</h2><span class="tag accent">FAVORITE</span></div>${parameters(record.params)}<p class="small">Random seed <code>${escape(record.batchSeed)}</code><br>${record.maxWidth ? `${record.maxWidth}px maximum width` : 'Original dimensions'} · ${escape(record.format)}</p><div class="actions"><a download href="${url(record.id)}/${url(record.file)}">Download ↗</a><a href="${url(record.id)}/metadata.json">Recipe ↗</a><a href="../generatedimages/${url(record.batch)}/index.html">Batch ↗</a></div></div></article>`).join('')}</section>` : '<div class="empty"><h2>Make something worth keeping.</h2><p>Open a batch and choose Save favorite. The image moves here with its parameters and gets staged in Git.</p><a class="button" href="../batches.html">Browse batches</a></div>'}`, '../', 'favorites');
}
module.exports = { shell, batch, favorites };
